### PR TITLE
feat: Merge tool

### LINKED ISSUE #22: Merge Conflicts
This [stackoverflow question](https://stackoverflow.com/questions/14904644/how-do-i-use-vimdiff-to-resolve-a-git-merge-conflict) is a great starting point for understanding how merge conflict resolution works with the builtin diffing tool.

One thing I noticed right away is that by default 4 splits appear. I'm not really a fan of this kind of resolution so I would propose either a traditional 2 or 3 way split approach. We could also try to replicate VSCode's way of doing this as it is very space efficient and based on my experience it is not too confusing.

We would also need to think about how we could reshape the API to support both normal diffing and merge conflict resolution.

@sindrets have you thought about how you want to implement this before?

### PR DESCRIPTION
**Pull request by sindrets**
<sup>(finally)</sup>

Resolves #22.

This has been one of the longest standing feature requests, so I'm happy to announce that the first version of the merge-tool is finally almost ready!

2022-09-03-220849_maim

This initial implementation offers three different 3-way diff layouts, one 4-way diff layout, and one plain single window layout (for when you prefer editing the conflict markers manually without the visual noise from diffs).

<details>
  <summary><b>Layout documentation dump:</b></summary>

```vimhelp
view.x.layout                                   *diffview-config-view.x.layout*
        Type: >
            "diff1_plain"
                | "diff2_horizontal"
                | "diff2_vertical"
                | "diff3_horizontal"
                | "diff3_vertical"
                | "diff3_mixed"
                | "diff4_mixed"
                | -1
<
        Default: (see example config above)

        This determines the layout used for diffs in the various different
        views. Some of the layouts are only applicable to certain types of
        views.

        If you set the layout to `-1`, the layout type will be derived from
        your |'diffopt'| (more specifically: whether or not you have
        `vertical` set).

        Layouts: ~
            Unless otherwise stated, the window symbols (A, B, C, D) represent
            the following versions of a file:

            In the diff_view and file_history_view:
              • A: Old state
              • B: New state

                                                *diffview-conflict-versions*
            In the merge_tool:
              • A: OURS (current branch)
              • B: LOCAL (the file as it currently exists on disk)
              • C: THEIRS (incoming branch)
              • D: BASE (common ancestor)

            {diff1_plain}
                Available for: merge_tool

                This is a plain, singular window. This is available in case
                you prefer to edit conflict markers manually without the
                visual noise from diffs.

                Window symbols:
                  • A: LOCAL

                ┌──────────────┐
                │              │
                │              │
                │      A       │
                │              │
                │              │
                └──────────────┘

            {diff2_horizontal}
                Available for: diff_view, file_history_view

                ┌──────┬───────┐
                │      │       │
                │      │       │
                │  A   │   B   │
                │      │       │
                │      │       │
                └──────┴───────┘

            {diff2_vertical}
                Available for: diff_view, file_history_view

                ┌──────────────┐
                │      A       │
                │              │
                ├──────────────┤
                │      B       │
                │              │
                └──────────────┘

            {diff3_horizontal}
                Available for: merge_tool

                ┌────┬────┬────┐
                │    │    │    │
                │    │    │    │
                │ A  │ B  │ C  │
                │    │    │    │
                │    │    │    │
                └────┴────┴────┘

            {diff3_vertical}
                Available for: merge_tool

                ┌──────────────┐
                │      A       │
                ├──────────────┤
                │      B       │
                ├──────────────┤
                │      C       │
                └──────────────┘

            {diff3_mixed}
                Available for: merge_tool

                ┌──────┬───────┐
                │  A   │   C   │
                │      │       │
                ├──────┴───────┤
                │      B       │
                │              │
                └──────────────┘

            {diff4_mixed}
                Available for: merge_tool

                ┌────┬────┬────┐
                │ A  │ D  │ C  │
                │    │    │    │
                ├────┴────┴────┤
                │      B       │
                │              │
                └──────────────┘

                                                *diffview-config-view.merge_tool.disable_diagnostics*
view.merge_tool.disable_diagnostics
        Type: `boolean`, Default: `true`

        Temporarily disable diagnostics for conflict buffers while in a
        diff_view. The diagnostics are enabled again when leaving or closing
        the view's tab page.
```

</details>

<br/>

<details>
  <summary style="cursor: pointer"><b>Layout showcase:</b></summary>

https://user-images.githubusercontent.com/2786478/188286499-effd4cb9-32dc-47ef-9b95-e85d3264bfeb.mp4

<p align="center">
  <b>Cycle trough the various different layouts with <code>g&ltC-x&gt</code></b>
</p>

---

2022-09-03-220849_maim

<p align="center">
  <b><code>diff1_plain</code> single window layout, using <a href="https://github.com/akinsho/git-conflict.nvim">git-conflict.nvim</a></b>
</p>

</details>

<br/>

<details>
  <summary style="cursor: pointer"><b>Relevant new config and keymaps:</b></summary>

```lua
require("diffview").setup({
  view = {
    -- Configure the layout and behavior of different types of views.
    -- Available layouts: 
    --  'diff1_plain'
    --    |'diff2_horizontal'
    --    |'diff2_vertical'
    --    |'diff3_horizontal'
    --    |'diff3_vertical'
    --    |'diff3_mixed'
    --    |'diff4_mixed'
    -- For more info, see |diffview-config-view.x.layout|.
    default = {
      -- Config for changed files, and staged files in diff views.
      layout = "diff2_horizontal",
    },
    merge_tool = {
      -- Config for conflicted files in diff views during a merge or rebase.
      layout = "diff3_horizontal",
      disable_diagnostics = true,   -- Temporarily disable diagnostics for conflict buffers while in the view.
    },
    file_history = {
      -- Config for changed files in file history views.
      layout = "diff2_horizontal",
    },
  },
  keymaps = {
    view = {
      ["g<C-x>"]     = actions.cycle_layout,              -- Cycle through available layouts.
      ["[x"]         = actions.prev_conflict,             -- In the merge_tool: jump to the previous conflict
      ["]x"]         = actions.next_conflict,             -- In the merge_tool: jump to the next conflict
      ["<leader>co"] = actions.conflict_choose("ours"),   -- Choose the OURS version of a conflict
      ["<leader>ct"] = actions.conflict_choose("theirs"), -- Choose the THEIRS version of a conflict
      ["<leader>cb"] = actions.conflict_choose("base"),   -- Choose the BASE version of a conflict
      ["<leader>ca"] = actions.conflict_choose("all"),    -- Choose all the versions of a conflict
      ["dx"]         = actions.conflict_choose("none"),   -- Delete the conflict region
    },
    diff1 = { --[[ Mappings in single window diff layouts ]] },
    diff2 = { --[[ Mappings in 2-way diff layouts ]] },
    diff3 = {
      -- Mappings in 3-way diff layouts
      { { "n", "x" }, "2do", actions.diffget("ours") },   -- Obtain the diff hunk from the OURS version of the file
      { { "n", "x" }, "3do", actions.diffget("theirs") }, -- Obtain the diff hunk from the THEIRS version of the file
    },
    diff4 = {
      -- Mappings in 4-way diff layouts
      { { "n", "x" }, "1do", actions.diffget("base") },   -- Obtain the diff hunk from the BASE version of the file
      { { "n", "x" }, "2do", actions.diffget("ours") },   -- Obtain the diff hunk from the OURS version of the file
      { { "n", "x" }, "3do", actions.diffget("theirs") }, -- Obtain the diff hunk from the THEIRS version of the file
    },
    file_panel = {
      ["g<C-x>"]        = actions.cycle_layout,
      ["[x"]            = actions.prev_conflict,
      ["]x"]            = actions.next_conflict,
    },
    file_history_panel = {
      ["g<C-x>"]        = actions.cycle_layout,
    },
  },
})
```

</details>

---

### Usage

If you call `:DiffviewOpen` during a merge or a rebase, the view will list the conflicted files in their own section. When opening a conflicted file, it will open in a 3-way diff allowing you to resolve the conflict with the context of the target branch's version (OURS, left), and the version from the branch which is being merged (THEIRS, right).

The conflicted file's entry in the file panel will show the remaining number of conflict markers (the number following the file name). If what follows the file name is instead an exclamation mark (`!`), this indicates that the file has not yet been opened, and the number of conflicts is unknown. If the sign is a check mark, this indicates that there are no more conflicts in the file.

You can jump between conflict markers with `]x` and `[x`. This works from the file panel as well. Further, in addition to the normal `:h copy-diffs` mappings you can use `2do` to obtain the hunk from the OURS side of the diff, `3do` to obtain the hunk from the THEIRS side of the diff, and - in a 4-way diff - `1do` to obtain the hunk from the BASE. See `:h diffview-conflict-versions` to tell what windows correspond with what version of the file.

Additionally there are mappings for operating directly on the conflict markers:

  - `<leader>co`: Choose the OURS version of the conflict.
  - `<leader>ct`: Choose the THEIRS version of the conflict.
  - `<leader>cb`: Choose the BASE version of the conflict.
  - `<leader>ca`: Choose all versions of the conflict (effectively
    just deletes the markers, leaving all the content).
  - `dx`: Choose none of the versions of the conflict (delete the
    conflict region).

For more info on these actions, see `:h diffview-actions-conflict_choose`.

### CODE REVIEW

**Comment by gegoune** [comment]
Our of interest, will there be a way to use this functionality from `git mergetool`?

**Comment by sindrets** [comment]
@gegoune Not right now at least. I haven't looked into it.

I'm not really sure it makes sense to use this plugin as the git-mergetool. I could be wrong as I haven't used the git-mergetool much, but I think it enforces a very specific workflow: it opens the merge-tool for a single file, then you handle the conflict for that file and close the merge-tool. Then you're prompted to open the merge-tool for the next conflicted file.

This is very different from the workflow design of diffview, where the whole point is that you get the full overview of the entire changeset, and are able to jump back and fourth between any of the files in the set during the process.

But I'm open to discuss it if people believe it should be supported :)

**Comment by 616b2f** [comment]
Is there a way to accept e.g. THEIRS for all conflicts of a file?

**Comment by sindrets** [comment]
@616b2f When you're in the file just do:

```
:!git checkout --theirs -- %
```

**Comment by 616b2f** [comment]
Thank you that will do, but I thaught may be it somehow possible to do it in the "file" view with something like "<leader>ct". Should I open a new Item for that?

**Comment by sindrets** [comment]
@616b2f Sure, we could add this as an action. Feel free to open a feature request. Or better yet: open a PR :)

**Pull request merged**
