### PR TITLE
feat: File History View

### LINKED ISSUE #42: Show diff of current file git history
It would be great if we could load every revision of a file into the left pane and then browse the diff.
I feel I could be able to do this if you are interested. (maybe with a little bit of guidance)

### PR DESCRIPTION
**Pull request by sindrets**
Resolves #42.

This implements a file history view that will list all commits that changed a given file or directory.

## Breaking Changes

This PR introduces some small breaking changes in the config, and for plugins integrating diffview.nvim.

The `use_icons` config table key has been moved out of the `file_panel` table. This has been done because `use_icons` now applies to other contexts than just the file panel. The correct way to configure this now is to set `use_icons` somewhere from the top level of the config table.

For plugins integrating diffview.nvim: Several of the git utilities have been refactored into their own namespace (`lua/diffview/git/`). I felt this was necessary due to the growing scope of the plugin. Most notably this means that the `Rev` class now resides in `lua/diffview/git/rev.lua`.

### `:DiffviewFileHistory [paths]`

Opens a new file history view that lists all commits that changed a given file or directory. If no `[paths]` are given, defaults to the current file. Multiple `[paths]` may be provided.

From the file history panel (the panel listing the commits) you can open an option panel by pressing `g!`. The option panel will allow you to change the flags that will be passed to `git-log`. A flag can be adjusted either by moving the cursor to its line followed by pressing `<Tab>`, or by using the mappings that are shown directly in the panel, preceding the flags' descriptions.

file-history-multi

### CODE REVIEW

**Comment by sindrets** [comment]
@simouel @tcstory If you have the time, it would be very helpful if you could give this PR a try and let me know if you encounter any problems. I've done a reasonable amount of testing myself, but given the nature of the task of parsing git logs, I'm sure there are cases I haven't considered.

**Comment by simouel** [comment]
I've done a quick test and it's working really good
Tested this way:  use {'sindrets/diffview.nvim', branch = 'feat/file-history' }

Tested current buffer and multiple paths

**Comment by lemontghe** [comment]
Hi, i had this error after upgrading:
```[Diffview.nvim] 'file_panel.use_icons' has been deprecated. See ':h diffview.changelog-64'.                          
Error detected while processing /home/le/.cache/nvim/plugged/indent-blankline.nvim/plugin/indent_blankline.vim:      
line   27:                                                                                                           
E5108: Error executing lua ...gged/indent-blankline.nvim/lua/indent_blankline/init.lua:45: Key not found: indent_blan
kline_space_char_blankline```

checkhealth output:
```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.8.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - elm            . . . . . 
  - rst            ✓ ✓ . . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - kotlin         ✓ . . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - query          x ✓ ✓ ✓ ✓ 
  - erlang         . . . . . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - teal           x x x ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

The following errors have been detected:
  - ERROR: query(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 448
  - ERROR: teal(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 1947
  - ERROR: teal(locals): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 33
  - ERROR: teal(folds): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 18

health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.5.0-dev+1318-g61aefaf29
  - INFO: Node version: v16.8.0

  - INFO: Script: /home/le/.cache/nvim/plugged/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.5.0-dev+1318-g61aefaf29
  - INFO: Plugin: 9716765


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

health#targets#check
========================================================================
  - WARNING: Conflicting mapping found:
    aa → :<C-U>call textobj#argument#(0, 1)<CR>
    a → {'argument': [{'s': ',', 'c': '[])]', 'o': '[([]'}]}
  - WARNING: Conflicting mapping found:
    ia → :<C-U>call textobj#argument#(1, 1)<CR>
    a → {'argument': [{'s': ',', 'c': '[])]', 'o': '[([]'}]}

health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - OK: Ueberzug is ready

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python version: 2.7.18
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v16.8.0
  - INFO: Nvim node.js host: /home/le/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for elm: ABI version 13
  - OK: Loaded parser for erlang: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for query: ABI version 13
  - OK: Loaded parser for rst: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for teal: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for c: ABI version 13```
  I also tried reinstalling or using the e0ffb1cb7c5ea9e693e5ee5ee3ce1e5f78916ed6 commit

**Comment by sindrets** [comment]
@lemontghe The only output here that is from diffview is this line:

```
[Diffview.nvim] 'file_panel.use_icons' has been deprecated. See ':h diffview.changelog-64'.
```

This is only a deprecation warning, and is not an error. As advised in the warning: read the changelog to see how to migrate your config.

The errors you are getting are clearly coming from `indent-blankline` and not diffview:

```
Error detected while processing /home/le/.cache/nvim/plugged/indent-blankline.nvim/plugin/indent_blankline.vim:      
line   27:                                                                                                           
E5108: Error executing lua ...gged/indent-blankline.nvim/lua/indent_blankline/init.lua:45: Key not found: indent_blan
kline_space_char_blankline
```

I would advise you to check the issue tracker over there instead, and possibly open a new issue if you can't find anything related to this.

**Comment by lemontghe** [comment]
> @lemontghe The only output here that is from diffview is this line:
> 
> ```
> [Diffview.nvim] 'file_panel.use_icons' has been deprecated. See ':h diffview.changelog-64'.
> ```
> 
> This is only a deprecation warning, and is not an error. As advised in the warning: read the changelog to see how to migrate your config.
> 
> The errors you are getting are clearly coming from `indent-blankline` and not diffview:
> 
> ```
> Error detected while processing /home/le/.cache/nvim/plugged/indent-blankline.nvim/plugin/indent_blankline.vim:      
> line   27:                                                                                                           
> E5108: Error executing lua ...gged/indent-blankline.nvim/lua/indent_blankline/init.lua:45: Key not found: indent_blan
> kline_space_char_blankline
> ```
> 
> I would advise you to check the issue tracker over there instead, and possibly open a new issue if you can't find anything related to this.

My bad i actually didn't read it trough, you just had to change the variable name.

**Pull request merged**
