### PR TITLE
refactor!: Flexible layout system.

### PR DESCRIPTION
**Pull request by sindrets**
This is a huge refactor that gives the layout system in the views far greater flexibility. The primary motivation behind this PR is the planned merge-tool (#22) that is going to make use of 3-way diffs. I want the conflicted files to appear in their own section in the normal Diffview, thus the views need to be able to restructure the layout dynamically depending on what entry is currently open. The current implementation is deeply tied to the 2-way diff layout, and it would be unfeasible to force it to conform to a bodged dynamic layout system without larger structural changes.

#### The only breaking change affects the action `view_windo`. This action is not in use by default, so you won't be affected unless you know that you've made use of it in your config.

Different entries in the same view may now use completely different window layouts. Thus the action `view_windo` has changed to reflect these changes. See `:h diffview-actions-view_windo` for more details on the new usage.

### CODE REVIEW

**Comment by melkster** [comment]
@sindrets After updating to the latest version of Diffview I now get the error `packer.nvim: Error running config for diffview.nvim: ...site/pack/packer/start/diffview.nvim/lua/diffview/hl.lua:240: invalid key: underlineline` whenever I launch Neovim 🤔

**Comment by sindrets** [comment]
@melkster What Neovim version are you on? The highlight attribute `underlineline` was added in March quite a while before the v0.7.0 release (which is the minimum required version for this plugin, as stated in the README).

**Comment by melkster** [comment]
I'm on nightly `NVIM v0.8.0-dev+580-g45ba2e147`, but I haven't updated in a while so maybe there's an issue with the commit I'm on

**Comment by sindrets** [comment]
Ah, I see that the attribute has been renamed in nightly: https://github.com/neovim/neovim/commit/995e4879153d0f4ea72dff446c175754a1873425

**Comment by sindrets** [comment]
@melkster Should be fixed now in the latest commit.

**Comment by melkster** [comment]
@sindrets Thanks!

**Pull request merged**
