### PR TITLE
fix: E21: Cannot make changes, 'modifiable' is off

### PR DESCRIPTION
**Pull request by cathaysia**
This example codes to fix https://github.com/sindrets/diffview.nvim/issues/159. So merge it or not up to you. :)

### CODE REVIEW

**Review by sindrets — CHANGES_REQUESTED** [review]
Thanks for PR! The buffers created from git history should remain un-modifiable. The root of the problem here is that the `:h modeline` in the file is trying to set the fileencoding of an un-modifiable buffer. I think we should just `pcall` the call to `filetype detect` instead, to catch the error.

**Comment by cathaysia** [comment]
In fact, if I remove https://github.com/sindrets/diffview.nvim/blob/1eb1e497e36eea455d85b7e83e4272222a882ffa/lua/diffview/views/file_entry.lua#L414 , another error will happen.

emm, this bug disappeared on my laptop. I cannot test this bug. So should we close this pr and https://github.com/sindrets/diffview.nvim/issues/159?

**Comment by sindrets** [comment]
@cathaysia Do not remove `filetype detect`. Just pcall it.

> another error will happen.

Yes, probably `do WinEnter` on L256 which will re-trigger the modeline. Just pcall that as well.

> emm, this bug disappeared on my laptop. I cannot test this bug.

Like I said, this is caused by modelines. You can easily create a repo that reproduces this with a simple script like:

```bash
#!/usr/bin/bash

rm -rf /tmp/pr160-repo
mkdir /tmp/pr160-repo
cd /tmp/pr160-repo
git init
echo ' vim:fileencoding=utf-8' > a
git add -A
git commit -am 'init'
```

Then open the `DiffviewFileHistory` for this repo, and you will see the error.

**Comment by cathaysia** [comment]
emm, I had give a try on pacll, this bug can be solved by `vim.schedule(pcall....`, but it will introduce another bug: if pcall failed, diffview will be blank when call DiffviewFileHistory:

图片

the codes are:

```lua
      vim.schedule(function()
        pcall(function()
          if api.nvim_buf_is_valid(bn) then
            vim.bo[bn].modifiable = true
            api.nvim_buf_set_lines(bn, 0, -1, false, result)
            vim.bo[bn].modifiable = false
            vim.api.nvim_buf_call(bn, function()
              vim.cmd("filetype detect")
            end)
            callback()
          end
        end)
      end)
```

So, may move move line 414 down be a better way:

```lua
          vim.bo[bn].modifiable = true
          api.nvim_buf_set_lines(bn, 0, -1, false, result)
          vim.api.nvim_buf_call(bn, function()
            vim.cmd("filetype detect")
          end)
          callback()
          vim.bo[bn].modifiable = false
```

**Comment by cathaysia** [comment]
In my opinion, set modifiable to false just to prevent user to modify diffview, so we can put this last.

**Comment by cathaysia** [comment]
Yes, what you say is the best solution.

I had give a try to move vim.bo[bn].modifiable = false down, or pcall(callback), but then diffview cannot deal with error modeline, the best solution is close modeline. :)

test code:

``` bash
#!/usr/bin/bash

rm -rf /tmp/pr160-repo
mkdir /tmp/pr160-repo
cd /tmp/pr160-repo
git init
echo ' vim:fileencoding=utf-16' > a
git add -A
git commit -am 'init'
```

**Pull request merged**
